---
title: "for Authorized Investigators"
author: "Andrea R Seisler"
date: "4/20/2020"
output: html_document
---

# Information for Authorized Investigators

## How do I add a supervised user to all of my group/lab data?  

## How do I add a supervised user to all shared Databrary data?  

## How do I add a user to a specific project  

## What happens if I leave my institution and no longer have Authorized Investigator Status?  

## What if I my institution requires me to submit an IRB just to access?    

Here is some language that should help you.  

### Recommended Abstract language  

The purpose of this application is to access the Databrary
(https://www.databrary.org/about/about-databrary.html), which is a digital data library specialized
for storing, managing, preserving, analyzing, and sharing video.
I do not currently have data to contribute to the library; however, I would like to have access to its
contents in order to browse the available data and potentially develop a research project. Once I have
a research proposal, I will submit a new protocol for IRB determination.  

### Access to Identifiers  

I will have access to  elements of dates (except for year) for dates directly related to an individual, including birth date,  Biometric identifiers, including finger and voice prints, and
 Full face photographic images and any comparable images.  
 
### Purpose of accessing Databrary  
The purpose of this application is to access the Databrary
(https://www.databrary.org/about/about-databrary.html), which is a digital data library specialized
for storing, managing, preserving, analyzing, and sharing video. I would like to have access to its
contents in order to browse the data and potentially develop a research idea to submit for IRB
approval in a separate application.

## When do I need to submit to the IRB to use secondary data from Databrary?  

You will need to submit to the IRB for secondary data use when you move from the preparatory to  research to the research phase. 

When you move from exploring the feasibility of a coding scheme to deciding to apply it systematically to a set of videos, that is when you would need to submit to the IRB. You must still protect the data during pre-research or research planning as you normally would for these sorts of data as outlined in the Databrary Access Agreement.

Keep in mind the following:

Is it Research?  

Research is a "systematic investigation, including research development, testing and evaluation, designed to develop or contribute to generalizable knowledge" [(45 CFR 46.102(l))](https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=83cd09e1c0f5c6937cd9d7513160fc3f&pitd=20180719&n=pt45.1.46&r=PART&ty=HTML#se45.1.46_1102).

Is it a Human Subject?  

A human subject is “a living individual about whom an investigator (whether professional or student) conducting research:

(i) obtains information or biospecimens through intervention or interaction with the individual, and uses, studies, or analyzes the information or biospecimens; or (ii) obtains, uses, studies, analyzes, or generates identifiable private information or identifiable biospecimens” [(45 CFR 46.102(e))](https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=83cd09e1c0f5c6937cd9d7513160fc3f&pitd=20180719&n=pt45.1.46&r=PART&ty=HTML#se45.1.46_1102).

When you can answer YES to these two questions you need to submit to your IRB. If you are not sure, contact your IRB and they can help you.


    
