---
title: ""
date:  "`r Sys.time()`"
output:
  html_document:
    toc: true
    toc_float: true
    number_sections: true
    toc_depth: 3
---

# Information for Institution Authorized Organizational Representatives  

Researchers seeking authorization to access Databrary must have their Databrary Access Agreement approved and signed by an authorized organizational representative, or AOR, of their institution. Once an institution has signed the agreement, the individual becomes an authorized investigator.

## What is an Authorized Organizational Representative?

- put link to Glossary definition here

## What type(s) of Institutions may participate in Databrary?


## Overview of the Databrary Access Agreement
The Databrary Access Agreement grants user and contributor privileges to all shared data in Databrary. Once the agreement is finalized, authorized investigator can access identifiable data that is shared. Below is a summary, but all details are located in documents located in the [Templates]() and [Policies]() sections

Approval for research involving human subjects is **not** required by Databrary in order to become an authorized investigator. 

Institutions should remember that authorized investigators agree to seek whatever approvals are required by their institution for their use of Databrary. Typically, contributing data and conducting research using Databrary resources require institutional approval for research involving human subjects. However, many uses of Databrary are for pre-research or non-research purposes (e.g. browsing data for ideas, getting video clips for teaching or talks, learning about procedures or methods) and do not typically require institutional approval for research involving human subjects.

When Authorizing Investigators
The institution confirms the eligibility of its investigators by:

Verifying that authorized investigators are eligible to conduct independent research at the institution.
Validating that authorized investigators have research ethics training that meets the institution's standards.
The institution:

Maintains an ethics or institutional review board that reviews and approves research involving human subjects.
Grants authorized investigators the responsibility to choose and manage affiliates who meet Databrary's qualifications and who agree to follow Databrary's ethical principles. The institution holds authorized investigators responsible for the conduct of affiliates they select.
Accepts responsibility for its authorized investigator(s) actions related to the use of Databrary.
Data Contribution and Use
The institution:

Asserts that it has the rights to share with Databrary any data the authorized investigator contributes; no other entity or individual has ownership rights that prevent the authorized investigator from contributing data to Databrary.
Agrees to allow use of the data exclusively for the purpose of scientific research or education under the auspices of an academic, research, government, health, or commercial entity (but in the last case, solely for non-commercial purposes unless allowed under the terms of a separate agreement).
Agrees not to sell or trade data or use it for other commercial purposes.
Grants each authorized investigator authority to decide when and with whom the authorized investigator wishes to share data, and the institution holds the authorized investigator responsible for the use of shared data.
Agrees to follow all relevant national, state, and local laws and regulations that pertain to the use of research data.
Confidentiality and Ethics
The institution agrees to inform Databrary of any suspected violation of confidentiality or ethics. If Databrary determines that an authorized investigator at the institution has violated the terms of the Databrary Access Agreement or other Databrary policies, Databrary may remove the data in question and/or deny the authorized investigator or the institution access to Databrary, temporarily or permanently.

Any violation may be reported to the official at the institution charged with handling violations of research ethics. The Institution may request information from Databrary about the authorized investigator's use or their Affiliate's use of the library.

If denied access to Databrary, authorized investigators or the institution may request a review.

Each party shall be responsible for its negligent acts or omissions and the negligent acts or omissions of its employees, officers, or director's, to the extent allowed by law.






### Templates

- Databrary Access Agreement

- Statement of Rights and Responsibilities - Annex I

- Additional Authorized Investigators - Annex II

- Databrary Access Guide - Annex III

### Policies

- Terms of Use

- Privacy Policy

- Data Security

Data and metadata stored in Databrary are subject to the security policies and best practices implemented by NYU. For more information about these policies and services, please visit NYU ITS Computer & Network Security at http://www.nyu.edu/its/security/.

- [User Guide - for institutions](https://www.databrary.org/resources/guide/institutions.html)

