---
title: "HowTo"
output: html_document
---

# How to

## Get Authorized
- get authorized as an Authorized Investigator

- have a supervised user create an account and request access from their Sponsoring Authorized Investigator

- can an Authorized Investigator add Supervised Users

## Create/Edit Projects

- create a new project
- update the citation of my project
- add cited authors vs. non cited researchers
- upload participant data
- What file types can be uploaded? (https://nyu.databrary.org/asset/formats)

## Document permission from participants

### Consenting to participate is separate from releasing data for sharing

Researchers should not worry that participants will decide not to enter a study because they are being asked to share their information. Consenting to participate in a study is an entirely separate decision for participants from giving permission to share their data. They can agree to participate in the study and choose to not release their data for sharing.

Because of this, we recommend that researchers introduce the Databrary Release after the recording--such as at the end of a session, visit, or longitudinal study. By asking participants about sharing with Databrary after the recording is finished, participants will know what was done during the session and have a clearer understanding of what they would be agreeing to share. Even this is entirely adaptable, as there may be other reasons that asking at the end is undesirable or infeasible.

The following considerations may apply when deciding when to introduce the Release:

  - If the researcher would like to give participants the option to select which part or parts of the session to share, the form could be given at the end of each section. Alternatively, the form could be adapted to allow participants to answer about each section separately at the end of the entire session.  
  - If there are activities or data of a sensitive nature in some portion of the session, the researcher may choose not to share that portion of the sessions. In this case, researchers may prefer to adapt the form to indicate that the sensitive portion will not be shared.
  - The data contributor can always choose not to share certain parts of the video even if the participant agreed to share them.
  - There may be some cases where it is simpler or necessary to offer the Databrary Release at the beginning of the study, such as in in classroom recordings or other group settings.
  
Databrary does **not** require contributors to have used the Databrary Release, or that researchers ask about sharing at the end.

### Correlating with release levels  

The template is designed to help researchers standardize the language used and know exactly which release level to tag each session with based on their participants' decisions.

No matter what form or language is used to obtain releases for Databrary sharing, contributors must determine which release level each participant agreed to and tag each session (or portion of a session) with the correct level of sharing.

### Samples and Examples

Sample participant release script (upload)
Example videos of the release process (upload)
